### ISSUE TITLE
Demo offline

### ISSUE THREAD

**Issue by valerio-bozzolan** [makinacorpus/Leaflet.LineExtremities#16]
Hi all! I've clicked on the demo link in the README but it's not online. Are you aware of that?

I was just interested in add an operational demo link from this page:

https://leafletjs.com/plugins.html

Thank you so much for your work on this plugin! :)

**Comment by Bo-Duke** [comment]
Indeed the link in Readme redirected to the wrong domain that's now corrected.

The link in the "about" section was up to date though :)

Thank you!
