### ISSUE TITLE
Show extremities with the same apparence as line

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Leaflet.LineExtremities#2]

**Comment by fredericbonifas** [comment]
I imagine two ways to achieve this:
- define automatically one marker per polyline, fitting its style (color, opacity etc). This could lead to many redundant markers if polylines have often the same style
- define manually a few markers with custom style at first, and then assign them to the polylines.

This will depend on the use of the plugin, whether lines have an homogeneous style or each line has its own style.

@leplatrem do you have an opinion ?

**Comment by leplatrem** [comment]
Indeed, the primary intended use of this plugin is to show extremities on a group layer of many lines. And not really on individual layers.

I would suggest we go for the first option, with a special behaviour for group layers that have a common style for all their children layers.
But if it's too much pain with the current design, we can go easily with the second option...
