### ISSUE TITLE
Extremities misplaced ?

### ISSUE THREAD

**Issue by leplatrem** [makinacorpus/Leaflet.LineExtremities#3]
End is ok
![slection_285](https://cloud.githubusercontent.com/assets/546692/2692579/91f8df8e-c3a4-11e3-96d8-5ef417224abe.png)

Start looks misplaced ?
![slection_284](https://cloud.githubusercontent.com/assets/546692/2692580/94a92cd4-c3a4-11e3-8721-dce8db143d50.png)

**Comment by fredericbonifas** [comment]
Two problems : 
- marker isn't well centered
- 'stroke-linecap' attribute on the polyline has the value round as shown below
  ![image](https://cloud.githubusercontent.com/assets/1278216/2718776/60ad44c2-c554-11e3-8b29-d37a6121d329.png)
